# Generated by Django 4.1.5 on 2023-09-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
